version: '3.9'
services:
  udp-server:
    build:
      context: .
      dockerfile: Dockerfile-udp-server
    networks:
      - udp-network
    ports:
      - "8081:8081/udp"
  udp-client:
    build:
      context: .
      dockerfile: Dockerfile-udp-client
    networks:
      - udp-network
    depends_on:
      - udp-server
    deploy:
      replicas: 5
  tcp-server:
    build:
      context: .
      dockerfile: Dockerfile-tcp-server
    networks:
      - tcp-network
    ports:
      - "8080:8080"
  tcp-client:
    build:
      context: .
      dockerfile: Dockerfile-tcp-client
    networks:
      - tcp-network
    depends_on:
      - tcp-server
    deploy:
      replicas: 5
networks:
  udp-network:
    driver: bridge
  tcp-network:
    driver: bridge